//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cv.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Userinfo
    {
        public int UserInfoID { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string PhoneNumber { get; set; }
        public string Adress { get; set; }
        public byte[] UserImage { get; set; }
        public Nullable<int> fk_GenderID { get; set; }
        public Nullable<int> fk_UserID { get; set; }
    
        public virtual tbl_Gender tbl_Gender { get; set; }
        public virtual tbl_Member tbl_Member { get; set; }
    }
}
